<Project>
  <PropertyGroup>
    <LaplaceManagedBuildRoot Condition="'$(LaplaceManagedBuildRoot)' == ''">/opt/laplace/work/laplace-refactor/build/managed</LaplaceManagedBuildRoot>
    <BaseOutputPath>$(LaplaceManagedBuildRoot)/$(MSBuildProjectName)/bin/</BaseOutputPath>
    <BaseIntermediateOutputPath>$(LaplaceManagedBuildRoot)/$(MSBuildProjectName)/obj/</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
