#!/usr/bin/env python3
"""Generate the native Unicode source authority table from the pinned contracts."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


CONTRACT_NAMES = (
    "unicode-source.json",
    "unicode-atom-record.json",
    "ducet-totalization.json",
    "super-fibonacci-hopf.json",
    "hilbert-numeric.json",
)


def bytes_initializer(value: bytes) -> str:
    return ", ".join(f"0x{byte:02x}u" for byte in value)


def c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def generate(contract_root: Path) -> str:
    contract_bytes = {
        name: (contract_root / name).read_bytes() for name in CONTRACT_NAMES
    }
    source = json.loads(contract_bytes["unicode-source.json"])
    if source.get("schema") != "laplace.unicode-source-contract/v1":
        raise ValueError("unsupported Unicode source contract")
    files = source.get("files")
    if not isinstance(files, list) or len(files) != 32:
        raise ValueError("Unicode source contract must contain exactly 32 files")
    markers = {
        item["path"]: item["contains"]
        for item in source.get("version_markers", [])
        if "contains" in item
    }
    lines = [
        "/* Generated by tools/contracts/generate-unicode-source.py.",
        " * Sources: contracts/unicode-source.json, unicode-atom-record.json,",
        " * ducet-totalization.json, super-fibonacci-hopf.json, hilbert-numeric.json.",
        " * Do not edit. */",
        "#ifndef LAPLACE_GENERATED_UNICODE_SOURCE_MANIFEST_H",
        "#define LAPLACE_GENERATED_UNICODE_SOURCE_MANIFEST_H",
        "",
        "#include <stdint.h>",
        "",
        "typedef struct laplace_unicode_generated_source_file {",
        "    const char* relative_path;",
        "    const char* version_marker;",
        "    uint64_t expected_bytes;",
        "    uint8_t expected_sha256[32];",
        "} laplace_unicode_generated_source_file;",
        "",
        f"#define LAPLACE_UNICODE_GENERATED_SOURCE_COUNT {len(files)}u",
        f"#define LAPLACE_UNICODE_GENERATED_VERSION {c_string(source['unicode_version'])}",
        "",
        "static const laplace_unicode_generated_source_file",
        "laplace_unicode_generated_sources[LAPLACE_UNICODE_GENERATED_SOURCE_COUNT] = {",
    ]
    for item in files:
        digest = bytes.fromhex(item["sha256"])
        if len(digest) != 32 or item["bytes"] < 0:
            raise ValueError(f"invalid source entry: {item!r}")
        marker = markers.get(item["path"], "")
        lines.append(
            "    {"
            f"{c_string(item['path'])}, {c_string(marker)}, "
            f"UINT64_C({item['bytes']}), {{{bytes_initializer(digest)}}}" + "},"
        )
    lines.extend([
        "};",
        "",
        "typedef struct laplace_unicode_generated_contract_file {",
        "    const char* name;",
        "    uint8_t sha256[32];",
        "} laplace_unicode_generated_contract_file;",
        "",
        f"#define LAPLACE_UNICODE_GENERATED_CONTRACT_COUNT {len(CONTRACT_NAMES)}u",
        "static const laplace_unicode_generated_contract_file",
        "laplace_unicode_generated_contracts[LAPLACE_UNICODE_GENERATED_CONTRACT_COUNT] = {",
    ])
    for name in CONTRACT_NAMES:
        digest = hashlib.sha256(contract_bytes[name]).digest()
        lines.append(
            f"    {{{c_string(name)}, {{{bytes_initializer(digest)}}}}},"
        )
    lines.extend(["};", "", "#endif", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--contracts", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    content = generate(args.contracts)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
