function(laplace_configure_tabular_source_contract contract_path output)
    file(READ "${contract_path}" contract)
    string(JSON schema GET "${contract}" schema)
    string(JSON abi_major GET "${contract}" abi major)
    string(JSON abi_minor GET "${contract}" abi minor)
    string(JSON artifact_graph_domain GET "${contract}" identity artifact_graph_domain)
    string(JSON source_graph_domain GET "${contract}" identity source_graph_domain)
    string(JSON source_domain GET "${contract}" identity source_domain)
    string(JSON reconstruction_domain GET "${contract}" identity reconstruction_domain)
    string(JSON mode_raw GET "${contract}" artifact_modes raw_octets)
    string(JSON mode_delimited GET "${contract}" artifact_modes utf8_delimited)
    string(JSON mode_fixed_width GET "${contract}" artifact_modes utf8_fixed_width)
    string(JSON terminator_none GET "${contract}" line_terminators none)
    string(JSON terminator_lf GET "${contract}" line_terminators lf)
    string(JSON terminator_crlf GET "${contract}" line_terminators crlf)
    if(NOT schema STREQUAL "laplace.tabular-source-contract/v1" OR
       NOT abi_major EQUAL 1 OR NOT abi_minor EQUAL 5 OR
       NOT mode_raw EQUAL 1 OR NOT mode_delimited EQUAL 2 OR
       NOT mode_fixed_width EQUAL 3 OR
       NOT terminator_none EQUAL 0 OR NOT terminator_lf EQUAL 1 OR
       NOT terminator_crlf EQUAL 2)
        message(FATAL_ERROR "Tabular source contract changed incompatibly")
    endif()
    set(LAPLACE_TABULAR_SOURCE_ABI_MAJOR "${abi_major}")
    set(LAPLACE_TABULAR_SOURCE_ABI_MINOR "${abi_minor}")
    set(LAPLACE_TABULAR_ARTIFACT_GRAPH_DOMAIN "${artifact_graph_domain}")
    set(LAPLACE_TABULAR_SOURCE_GRAPH_DOMAIN "${source_graph_domain}")
    set(LAPLACE_TABULAR_SOURCE_DOMAIN "${source_domain}")
    set(LAPLACE_TABULAR_RECONSTRUCTION_DOMAIN "${reconstruction_domain}")
    set(LAPLACE_TABULAR_ARTIFACT_RAW "${mode_raw}")
    set(LAPLACE_TABULAR_ARTIFACT_DELIMITED "${mode_delimited}")
    set(LAPLACE_TABULAR_ARTIFACT_FIXED_WIDTH "${mode_fixed_width}")
    set(LAPLACE_TABULAR_TERMINATOR_NONE "${terminator_none}")
    set(LAPLACE_TABULAR_TERMINATOR_LF "${terminator_lf}")
    set(LAPLACE_TABULAR_TERMINATOR_CRLF "${terminator_crlf}")
    configure_file("${CMAKE_SOURCE_DIR}/cmake/tabular_source.h.in" "${output}" @ONLY)
endfunction()
