function(laplace_configure_standing_calculation_contract contract_path output_path)
    file(READ "${contract_path}" contract_json)
    string(JSON schema GET "${contract_json}" schema)
    string(JSON version GET "${contract_json}" version)
    string(JSON algorithm GET "${contract_json}" algorithm)
    foreach(name IN ITEMS scale_center_binary64 scale_divisor_binary64 pi_binary64 maximum_bracket_steps maximum_iterations)
        string(JSON numeric_${name} GET "${contract_json}" numeric_contract ${name})
    endforeach()
    foreach(name IN ITEMS recipe recipe_admission outcome_mapping arena_scope coordinate state event input output receipt)
        string(JSON domain_${name} GET "${contract_json}" domains ${name})
    endforeach()
    foreach(name IN ITEMS confirm refute draw uncertain absent unknown denied exhausted invalid_execution)
        string(JSON outcome_${name} GET "${contract_json}" outcome_kinds ${name})
    endforeach()
    string(JSON flags_none GET "${contract_json}" flags none)
    if(NOT schema STREQUAL "laplace.standing-calculation/v1"
       OR NOT version EQUAL 1
       OR NOT algorithm STREQUAL "Glicko-2 March 22 2022 Illinois iteration")
        message(FATAL_ERROR "Unsupported standing-calculation contract")
    endif()
    if(NOT numeric_scale_center_binary64 STREQUAL "0x1.7700000000000p+10"
       OR NOT numeric_scale_divisor_binary64 STREQUAL "0x1.5b6f837b4a234p+7"
       OR NOT numeric_pi_binary64 STREQUAL "0x1.921fb54442d18p+1"
       OR NOT numeric_maximum_bracket_steps EQUAL 100
       OR NOT numeric_maximum_iterations EQUAL 100)
        message(FATAL_ERROR "Standing-calculation numeric contract changed")
    endif()
    set(expected 1)
    foreach(name IN ITEMS confirm refute draw uncertain absent unknown denied exhausted invalid_execution)
        if(NOT outcome_${name} EQUAL expected)
            message(FATAL_ERROR "Standing outcome assignments changed")
        endif()
        math(EXPR expected "${expected} + 1")
    endforeach()
    if(NOT flags_none EQUAL 0)
        message(FATAL_ERROR "Standing flags changed")
    endif()
    set(LAPLACE_STANDING_VERSION "${version}")
    set(LAPLACE_STANDING_SCALE_CENTER "${numeric_scale_center_binary64}")
    set(LAPLACE_STANDING_SCALE_DIVISOR "${numeric_scale_divisor_binary64}")
    set(LAPLACE_STANDING_PI "${numeric_pi_binary64}")
    set(LAPLACE_STANDING_MAX_BRACKET_STEPS "${numeric_maximum_bracket_steps}")
    set(LAPLACE_STANDING_MAX_ITERATIONS "${numeric_maximum_iterations}")
    foreach(name IN ITEMS recipe recipe_admission outcome_mapping arena_scope coordinate state event input output receipt)
        string(TOUPPER "${name}" symbol)
        set(LAPLACE_STANDING_${symbol}_DOMAIN "${domain_${name}}")
    endforeach()
    foreach(name IN ITEMS confirm refute draw uncertain absent unknown denied exhausted invalid_execution)
        string(TOUPPER "${name}" symbol)
        set(LAPLACE_STANDING_OUTCOME_${symbol} "${outcome_${name}}")
    endforeach()
    set(LAPLACE_STANDING_FLAGS_NONE "${flags_none}")
    get_filename_component(output_directory "${output_path}" DIRECTORY)
    file(MAKE_DIRECTORY "${output_directory}")
    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/standing_calculation.h.in" "${output_path}" @ONLY)
endfunction()
