include_guard(GLOBAL)

function(laplace_configure_world_admission_contract contract_path output)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${contract_path}")
    file(READ "${contract_path}" contract)
    string(JSON schema GET "${contract}" schema)
    string(JSON version GET "${contract}" version)
    string(JSON digest GET "${contract}" identity digest)
    string(JSON admission_domain GET "${contract}" identity admission_domain)
    string(JSON readback_domain GET "${contract}" identity readback_domain)
    string(JSON input_domain GET "${contract}" identity input_domain)
    string(JSON output_domain GET "${contract}" identity output_domain)
    string(JSON receipt_domain GET "${contract}" identity receipt_domain)
    string(JSON component_count LENGTH "${contract}" required_component_receipts)
    string(JSON flags_none GET "${contract}" flags none)
    if(NOT schema STREQUAL "laplace.world-admission-execution-contract/v1" OR
       NOT version EQUAL 1 OR NOT digest STREQUAL "BLAKE3-256" OR
       NOT component_count EQUAL 8 OR NOT flags_none EQUAL 0)
        message(FATAL_ERROR "World-admission execution contract changed incompatibly")
    endif()
    set(LAPLACE_WORLD_ADMISSION_VERSION "${version}")
    set(LAPLACE_WORLD_ADMISSION_ADMISSION_DOMAIN "${admission_domain}")
    set(LAPLACE_WORLD_ADMISSION_READBACK_DOMAIN "${readback_domain}")
    set(LAPLACE_WORLD_ADMISSION_INPUT_DOMAIN "${input_domain}")
    set(LAPLACE_WORLD_ADMISSION_OUTPUT_DOMAIN "${output_domain}")
    set(LAPLACE_WORLD_ADMISSION_RECEIPT_DOMAIN "${receipt_domain}")
    configure_file("${CMAKE_SOURCE_DIR}/cmake/world_admission.h.in" "${output}" @ONLY)
endfunction()
