function(laplace_configure_evidence_testimony_contract contract_path output_path)
    file(READ "${contract_path}" contract_json)
    string(JSON schema GET "${contract_json}" schema)
    string(JSON version GET "${contract_json}" version)
    string(JSON algorithm GET "${contract_json}" digest_algorithm)
    foreach(domain IN ITEMS identity input output receipt)
        string(JSON ${domain}_domain GET "${contract_json}" ${domain}_domain)
    endforeach()
    foreach(source_type IN ITEMS standard curated_dataset corpus direct_observation calculation model self_assertion external_provider)
        string(JSON source_${source_type} GET "${contract_json}" source_types ${source_type})
    endforeach()
    foreach(outcome IN ITEMS assertion measurement prediction observed_consequence mapping definition example counterexample unknown_boundary)
        string(JSON outcome_${outcome} GET "${contract_json}" outcome_types ${outcome})
    endforeach()
    foreach(disposition IN ITEMS persisted reused transformed lossy unsupported malformed unresolved rejected derived contradicted)
        string(JSON disposition_${disposition} GET "${contract_json}" dispositions ${disposition})
    endforeach()
    string(JSON flags_none GET "${contract_json}" flags none)
    if(NOT schema STREQUAL "laplace.evidence-testimony/v1" OR NOT version EQUAL 1
       OR NOT algorithm STREQUAL "BLAKE3-256")
        message(FATAL_ERROR "Unsupported evidence-testimony contract")
    endif()
    set(expected 1)
    foreach(value IN ITEMS
            source_standard source_curated_dataset source_corpus
            source_direct_observation source_calculation source_model
            source_self_assertion source_external_provider)
        if(NOT ${value} EQUAL expected)
            message(FATAL_ERROR "Evidence-testimony source-type assignments changed")
        endif()
        math(EXPR expected "${expected} + 1")
    endforeach()
    set(expected 1)
    foreach(value IN ITEMS
            outcome_assertion outcome_measurement outcome_prediction
            outcome_observed_consequence outcome_mapping outcome_definition
            outcome_example outcome_counterexample outcome_unknown_boundary)
        if(NOT ${value} EQUAL expected)
            message(FATAL_ERROR "Evidence-testimony outcome assignments changed")
        endif()
        math(EXPR expected "${expected} + 1")
    endforeach()
    set(expected 1)
    foreach(value IN ITEMS
            disposition_persisted disposition_reused disposition_transformed
            disposition_lossy disposition_unsupported disposition_malformed
            disposition_unresolved disposition_rejected disposition_derived
            disposition_contradicted)
        if(NOT ${value} EQUAL expected)
            message(FATAL_ERROR "Evidence-testimony disposition assignments changed")
        endif()
        math(EXPR expected "${expected} + 1")
    endforeach()
    if(NOT flags_none EQUAL 0)
        message(FATAL_ERROR "Evidence-testimony flags changed")
    endif()
    set(LAPLACE_EVIDENCE_TESTIMONY_VERSION "${version}")
    set(LAPLACE_EVIDENCE_TESTIMONY_IDENTITY_DOMAIN "${identity_domain}")
    set(LAPLACE_EVIDENCE_TESTIMONY_INPUT_DOMAIN "${input_domain}")
    set(LAPLACE_EVIDENCE_TESTIMONY_OUTPUT_DOMAIN "${output_domain}")
    set(LAPLACE_EVIDENCE_TESTIMONY_RECEIPT_DOMAIN "${receipt_domain}")
    foreach(source_type IN ITEMS standard curated_dataset corpus direct_observation calculation model self_assertion external_provider)
        string(TOUPPER "${source_type}" symbol)
        set(LAPLACE_EVIDENCE_SOURCE_${symbol} "${source_${source_type}}")
    endforeach()
    foreach(outcome IN ITEMS assertion measurement prediction observed_consequence mapping definition example counterexample unknown_boundary)
        string(TOUPPER "${outcome}" symbol)
        set(LAPLACE_EVIDENCE_OUTCOME_${symbol} "${outcome_${outcome}}")
    endforeach()
    foreach(disposition IN ITEMS persisted reused transformed lossy unsupported malformed unresolved rejected derived contradicted)
        string(TOUPPER "${disposition}" symbol)
        set(LAPLACE_EVIDENCE_DISPOSITION_${symbol} "${disposition_${disposition}}")
    endforeach()
    set(LAPLACE_EVIDENCE_TESTIMONY_FLAGS_NONE "${flags_none}")
    get_filename_component(output_directory "${output_path}" DIRECTORY)
    file(MAKE_DIRECTORY "${output_directory}")
    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/evidence_testimony.h.in" "${output_path}" @ONLY)
endfunction()
