function(laplace_configure_trajectory_contract contract_path output_path)
    file(READ "${contract_path}" contract_json)

    string(JSON contract_schema GET "${contract_json}" schema)
    string(JSON slot_count GET "${contract_json}" carrier slot_count)
    string(JSON slot_bits GET "${contract_json}" carrier slot_bits)
    string(JSON payload_bits_per_slot GET "${contract_json}" carrier payload_bits_per_slot)
    string(JSON payload_bits GET "${contract_json}" carrier payload_bits)
    string(JSON exponent GET "${contract_json}" carrier binary64_exponent)
    string(JSON mantissa_bits GET "${contract_json}" carrier binary64_mantissa_bits)
    string(JSON lane128_bits GET "${contract_json}" payload lane128_bits)
    string(JSON ordinal_bits GET "${contract_json}" payload ordinal_bits)
    string(JSON run_bits GET "${contract_json}" payload run_bits)
    string(JSON metadata_bits GET "${contract_json}" payload metadata_bits)
    string(JSON has_atom_bit GET "${contract_json}" content_metadata has_atom_bit)
    string(JSON tier_shift GET "${contract_json}" content_metadata tier_shift)
    string(JSON tier_bits GET "${contract_json}" content_metadata tier_bits)
    string(JSON atom_shift GET "${contract_json}" content_metadata atom_shift)
    string(JSON atom_bits GET "${contract_json}" content_metadata atom_bits)
    string(JSON vector_entity GET "${contract_json}" vectors entity_hex)
    string(JSON vector_ordinal GET "${contract_json}" vectors ordinal)
    string(JSON vector_run GET "${contract_json}" vectors run)
    string(JSON vector_metadata GET "${contract_json}" vectors metadata_hex)
    string(JSON vector_x GET "${contract_json}" vectors slot_x_bits_hex)
    string(JSON vector_y GET "${contract_json}" vectors slot_y_bits_hex)
    string(JSON vector_z GET "${contract_json}" vectors slot_z_bits_hex)
    string(JSON vector_m GET "${contract_json}" vectors slot_m_bits_hex)

    if(NOT contract_schema STREQUAL "laplace.trajectory-contract/v1")
        message(FATAL_ERROR "Unsupported trajectory contract schema: ${contract_schema}")
    endif()
    if(NOT slot_count EQUAL 4 OR NOT slot_bits EQUAL 64
       OR NOT payload_bits_per_slot EQUAL 53 OR NOT payload_bits EQUAL 212
       OR NOT exponent EQUAL 1023 OR NOT mantissa_bits EQUAL 52)
        message(FATAL_ERROR "Trajectory carrier width contract changed")
    endif()
    if(NOT lane128_bits EQUAL 128 OR NOT ordinal_bits EQUAL 16
       OR NOT run_bits EQUAL 16 OR NOT metadata_bits EQUAL 52)
        message(FATAL_ERROR "Trajectory payload field widths changed")
    endif()
    if(NOT has_atom_bit EQUAL 0 OR NOT tier_shift EQUAL 1
       OR NOT tier_bits EQUAL 5 OR NOT atom_shift EQUAL 31
       OR NOT atom_bits EQUAL 21)
        message(FATAL_ERROR "Content trajectory metadata assignments changed")
    endif()

    set(LAPLACE_TRAJECTORY_SLOT_COUNT "${slot_count}")
    set(LAPLACE_TRAJECTORY_PAYLOAD_BITS_PER_SLOT "${payload_bits_per_slot}")
    set(LAPLACE_TRAJECTORY_PAYLOAD_BITS "${payload_bits}")
    set(LAPLACE_TRAJECTORY_BINARY64_EXPONENT "${exponent}")
    set(LAPLACE_TRAJECTORY_BINARY64_MANTISSA_BITS "${mantissa_bits}")
    set(LAPLACE_TRAJECTORY_METADATA_BITS "${metadata_bits}")
    set(LAPLACE_TRAJECTORY_HAS_ATOM_BIT "${has_atom_bit}")
    set(LAPLACE_TRAJECTORY_TIER_SHIFT "${tier_shift}")
    math(EXPR LAPLACE_TRAJECTORY_TIER_MASK "(1 << ${tier_bits}) - 1")
    set(LAPLACE_TRAJECTORY_ATOM_SHIFT "${atom_shift}")
    math(EXPR LAPLACE_TRAJECTORY_ATOM_MASK "(1 << ${atom_bits}) - 1")
    set(LAPLACE_TRAJECTORY_VECTOR_ENTITY_HEX "${vector_entity}")
    set(LAPLACE_TRAJECTORY_VECTOR_ORDINAL "${vector_ordinal}")
    set(LAPLACE_TRAJECTORY_VECTOR_RUN "${vector_run}")
    set(LAPLACE_TRAJECTORY_VECTOR_METADATA_HEX "${vector_metadata}")
    set(LAPLACE_TRAJECTORY_VECTOR_X_HEX "${vector_x}")
    set(LAPLACE_TRAJECTORY_VECTOR_Y_HEX "${vector_y}")
    set(LAPLACE_TRAJECTORY_VECTOR_Z_HEX "${vector_z}")
    set(LAPLACE_TRAJECTORY_VECTOR_M_HEX "${vector_m}")
    get_filename_component(output_directory "${output_path}" DIRECTORY)
    file(MAKE_DIRECTORY "${output_directory}")
    configure_file(
        "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/trajectory.h.in"
        "${output_path}"
        @ONLY)
endfunction()
