function(laplace_configure_evidence_lineage_contract contract_path output_path)
    file(READ "${contract_path}" contract_json)
    string(JSON schema GET "${contract_json}" schema)
    string(JSON version GET "${contract_json}" version)
    string(JSON algorithm GET "${contract_json}" digest_algorithm)
    string(JSON node_domain GET "${contract_json}" identity_domain)
    string(JSON receipt_domain GET "${contract_json}" receipt_domain)
    string(JSON record_node GET "${contract_json}" record_kinds node)
    string(JSON record_edge GET "${contract_json}" record_kinds dependence_edge)
    foreach(kind IN ITEMS observed testimony calculation derivation model_behavior unknown contradiction)
        string(JSON epistemic_${kind} GET "${contract_json}" epistemic_kinds ${kind})
    endforeach()
    string(JSON flags_none GET "${contract_json}" flags none)
    if(NOT schema STREQUAL "laplace.evidence-lineage/v1" OR NOT version EQUAL 1
       OR NOT algorithm STREQUAL "BLAKE3-256")
        message(FATAL_ERROR "Unsupported evidence-lineage contract")
    endif()
    if(NOT record_node EQUAL 1 OR NOT record_edge EQUAL 2
       OR NOT epistemic_observed EQUAL 1 OR NOT epistemic_testimony EQUAL 2
       OR NOT epistemic_calculation EQUAL 3 OR NOT epistemic_derivation EQUAL 4
       OR NOT epistemic_model_behavior EQUAL 5 OR NOT epistemic_unknown EQUAL 6
       OR NOT epistemic_contradiction EQUAL 7 OR NOT flags_none EQUAL 0)
        message(FATAL_ERROR "Evidence-lineage numeric assignments changed")
    endif()
    set(LAPLACE_EVIDENCE_LINEAGE_VERSION "${version}")
    set(LAPLACE_EVIDENCE_NODE_DOMAIN "${node_domain}")
    set(LAPLACE_EVIDENCE_RECEIPT_DOMAIN "${receipt_domain}")
    set(LAPLACE_EVIDENCE_RECORD_NODE "${record_node}")
    set(LAPLACE_EVIDENCE_RECORD_DEPENDENCE_EDGE "${record_edge}")
    set(LAPLACE_EVIDENCE_KIND_OBSERVED "${epistemic_observed}")
    set(LAPLACE_EVIDENCE_KIND_TESTIMONY "${epistemic_testimony}")
    set(LAPLACE_EVIDENCE_KIND_CALCULATION "${epistemic_calculation}")
    set(LAPLACE_EVIDENCE_KIND_DERIVATION "${epistemic_derivation}")
    set(LAPLACE_EVIDENCE_KIND_MODEL_BEHAVIOR "${epistemic_model_behavior}")
    set(LAPLACE_EVIDENCE_KIND_UNKNOWN "${epistemic_unknown}")
    set(LAPLACE_EVIDENCE_KIND_CONTRADICTION "${epistemic_contradiction}")
    set(LAPLACE_EVIDENCE_FLAGS_NONE "${flags_none}")
    get_filename_component(output_directory "${output_path}" DIRECTORY)
    file(MAKE_DIRECTORY "${output_directory}")
    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/evidence_lineage.h.in" "${output_path}" @ONLY)
endfunction()
