include_guard(GLOBAL)

function(laplace_remove_dependency_compile_flag target flag reason)
    if(NOT TARGET "${target}")
        message(FATAL_ERROR "Cannot normalize missing dependency target: ${target}")
    endif()
    get_target_property(current_flags "${target}" COMPILE_FLAGS)
    if(NOT current_flags)
        return()
    endif()
    separate_arguments(current_flag_list NATIVE_COMMAND "${current_flags}")
    list(FIND current_flag_list "${flag}" flag_index)
    if(flag_index EQUAL -1)
        message(FATAL_ERROR
            "Expected dependency flag ${flag} is absent from ${target}; review compatibility rule: ${reason}")
    endif()
    list(REMOVE_ITEM current_flag_list "${flag}")
    list(JOIN current_flag_list " " normalized_flags)
    set_target_properties("${target}" PROPERTIES COMPILE_FLAGS "${normalized_flags}")
    message(STATUS "Removed unsupported ${flag} from ${target}: ${reason}")
endfunction()

function(laplace_add_dependency_compile_option target option reason)
    if(NOT TARGET "${target}")
        message(FATAL_ERROR "Cannot normalize missing dependency target: ${target}")
    endif()
    target_compile_options("${target}" PRIVATE "${option}")
    message(STATUS "Added ${option} to ${target}: ${reason}")
endfunction()
