function(laplace_configure_execution_contract contract_path output_path)
    file(READ "${contract_path}" contract_json)

    string(JSON contract_schema GET "${contract_json}" schema)
    string(JSON major GET "${contract_json}" version major)
    string(JSON minor GET "${contract_json}" version minor)
    string(JSON core_unknown GET "${contract_json}" core_kinds unknown)
    string(JSON core_performance GET "${contract_json}" core_kinds performance)
    string(JSON core_efficiency GET "${contract_json}" core_kinds efficiency)
    string(JSON cache_data GET "${contract_json}" cache_kinds data)
    string(JSON cache_instruction GET "${contract_json}" cache_kinds instruction)
    string(JSON cache_unified GET "${contract_json}" cache_kinds unified)
    string(JSON processor_online GET "${contract_json}" processor_flags online)
    string(JSON processor_allowed GET "${contract_json}" processor_flags allowed)
    string(JSON topology_affinity GET "${contract_json}" topology_flags affinity_constrained)
    string(JSON topology_memory GET "${contract_json}" topology_flags memory_constrained)
    string(JSON topology_hybrid GET "${contract_json}" topology_flags hybrid_cores)
    string(JSON isa_sse2 GET "${contract_json}" isa_flags x86_sse2)
    string(JSON isa_avx GET "${contract_json}" isa_flags x86_avx)
    string(JSON isa_avx2 GET "${contract_json}" isa_flags x86_avx2)
    string(JSON isa_avx512f GET "${contract_json}" isa_flags x86_avx512f)
    string(JSON isa_fma GET "${contract_json}" isa_flags x86_fma)
    string(JSON isa_bmi2 GET "${contract_json}" isa_flags x86_bmi2)
    string(JSON isa_neon GET "${contract_json}" isa_flags arm_neon)

    if(NOT contract_schema STREQUAL "laplace.execution-contract/v1")
        message(FATAL_ERROR "Unsupported execution contract schema: ${contract_schema}")
    endif()
    if(NOT major EQUAL 1 OR NOT minor EQUAL 0)
        message(FATAL_ERROR "Current execution contract version must remain 1.0")
    endif()
    if(NOT core_unknown EQUAL 0 OR NOT core_performance EQUAL 1
       OR NOT core_efficiency EQUAL 2)
        message(FATAL_ERROR "Execution core-kind assignments changed")
    endif()
    if(NOT cache_data EQUAL 1 OR NOT cache_instruction EQUAL 2
       OR NOT cache_unified EQUAL 3)
        message(FATAL_ERROR "Execution cache-kind assignments changed")
    endif()
    if(NOT processor_online EQUAL 1 OR NOT processor_allowed EQUAL 2
       OR NOT topology_affinity EQUAL 1 OR NOT topology_memory EQUAL 2
       OR NOT topology_hybrid EQUAL 4 OR NOT isa_sse2 EQUAL 1
       OR NOT isa_avx EQUAL 2 OR NOT isa_avx2 EQUAL 4
       OR NOT isa_avx512f EQUAL 8 OR NOT isa_fma EQUAL 16
       OR NOT isa_bmi2 EQUAL 32 OR NOT isa_neon EQUAL 64)
        message(FATAL_ERROR "Execution flag assignments changed")
    endif()

    set(LAPLACE_EXECUTION_MAJOR "${major}")
    set(LAPLACE_EXECUTION_MINOR "${minor}")
    set(LAPLACE_EXECUTION_CORE_UNKNOWN "${core_unknown}")
    set(LAPLACE_EXECUTION_CORE_PERFORMANCE "${core_performance}")
    set(LAPLACE_EXECUTION_CORE_EFFICIENCY "${core_efficiency}")
    set(LAPLACE_EXECUTION_CACHE_DATA "${cache_data}")
    set(LAPLACE_EXECUTION_CACHE_INSTRUCTION "${cache_instruction}")
    set(LAPLACE_EXECUTION_CACHE_UNIFIED "${cache_unified}")
    set(LAPLACE_EXECUTION_PROCESSOR_ONLINE "${processor_online}")
    set(LAPLACE_EXECUTION_PROCESSOR_ALLOWED "${processor_allowed}")
    set(LAPLACE_EXECUTION_TOPOLOGY_AFFINITY_CONSTRAINED "${topology_affinity}")
    set(LAPLACE_EXECUTION_TOPOLOGY_MEMORY_CONSTRAINED "${topology_memory}")
    set(LAPLACE_EXECUTION_TOPOLOGY_HYBRID_CORES "${topology_hybrid}")
    set(LAPLACE_EXECUTION_ISA_X86_SSE2 "${isa_sse2}")
    set(LAPLACE_EXECUTION_ISA_X86_AVX "${isa_avx}")
    set(LAPLACE_EXECUTION_ISA_X86_AVX2 "${isa_avx2}")
    set(LAPLACE_EXECUTION_ISA_X86_AVX512F "${isa_avx512f}")
    set(LAPLACE_EXECUTION_ISA_X86_FMA "${isa_fma}")
    set(LAPLACE_EXECUTION_ISA_X86_BMI2 "${isa_bmi2}")
    set(LAPLACE_EXECUTION_ISA_ARM_NEON "${isa_neon}")
    get_filename_component(output_directory "${output_path}" DIRECTORY)
    file(MAKE_DIRECTORY "${output_directory}")
    configure_file(
        "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/execution.h.in"
        "${output_path}"
        @ONLY)
endfunction()
