function(laplace_configure_stock_recipe_contract contract_path output_path)
    file(READ "${contract_path}" contract_json)
    string(JSON schema GET "${contract_json}" schema)
    string(JSON version GET "${contract_json}" version)
    if(NOT schema STREQUAL "laplace.stock-recipe-catalog/v1" OR NOT version EQUAL 1)
        message(FATAL_ERROR "Unsupported stock-recipe contract")
    endif()
    foreach(name IN ITEMS recipe perfcache_plane catalog)
        string(JSON domain_${name} GET "${contract_json}" domains ${name})
        string(TOUPPER "${name}" symbol)
        set(LAPLACE_STOCK_${symbol}_DOMAIN "${domain_${name}}")
    endforeach()
    foreach(name IN ITEMS source release collection digital_object structural_region semantic_construction)
        string(JSON scope_${name} GET "${contract_json}" scope_kinds ${name})
        string(TOUPPER "${name}" symbol)
        set(LAPLACE_STOCK_SCOPE_${symbol} "${scope_${name}}")
    endforeach()
    foreach(name IN ITEMS recipe perfcache_plane)
        string(JSON item_${name} GET "${contract_json}" item_kinds ${name})
        string(TOUPPER "${name}" symbol)
        set(LAPLACE_STOCK_ITEM_${symbol} "${item_${name}}")
    endforeach()
    string(JSON LAPLACE_STOCK_FLAGS_NONE GET "${contract_json}" flags none)
    set(LAPLACE_STOCK_VERSION "${version}")
    get_filename_component(output_directory "${output_path}" DIRECTORY)
    file(MAKE_DIRECTORY "${output_directory}")
    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/stock_recipe.h.in" "${output_path}" @ONLY)
endfunction()
