function(laplace_configure_framework_contract contract_path output_path)
    file(READ "${contract_path}" contract_json)

    string(JSON contract_schema GET "${contract_json}" schema)
    string(JSON major GET "${contract_json}" version major)
    string(JSON minor GET "${contract_json}" version minor)
    foreach(epoch IN ITEMS source identity geometry evidence firmware dependency database perfcache numeric package)
        string(JSON epoch_${epoch} GET "${contract_json}" epoch_slots ${epoch})
    endforeach()
    string(JSON context_bootstrap GET "${contract_json}" context_flags bootstrap)
    string(JSON context_read_only GET "${contract_json}" context_flags read_only)
    string(JSON batch_none GET "${contract_json}" canonical_batch_flags none)
    string(JSON stream_none GET "${contract_json}" canonical_stream_flags none)
    string(JSON effect_none GET "${contract_json}" effect_dispositions none)
    string(JSON effect_staged GET "${contract_json}" effect_dispositions staged_inert)
    string(JSON effect_admitted GET "${contract_json}" effect_dispositions activation_admitted)
    string(JSON effect_activated GET "${contract_json}" effect_dispositions activated)
    string(JSON sink_major GET "${contract_json}" sink_abi major)
    string(JSON sink_minor GET "${contract_json}" sink_abi minor)
    string(JSON activation_provider_major GET "${contract_json}" activation_provider_abi major)
    string(JSON activation_provider_minor GET "${contract_json}" activation_provider_abi minor)
    string(JSON activation_none GET "${contract_json}" activation_flags none)
    string(JSON digest_algorithm GET "${contract_json}" digest algorithm)
    string(JSON digest_bytes GET "${contract_json}" digest bytes)

    if(NOT contract_schema STREQUAL "laplace.framework-contract/v1")
        message(FATAL_ERROR "Unsupported framework contract schema: ${contract_schema}")
    endif()
    if(NOT major EQUAL 1 OR NOT minor EQUAL 2
       OR NOT sink_major EQUAL 1 OR NOT sink_minor EQUAL 0
       OR NOT activation_provider_major EQUAL 1
       OR NOT activation_provider_minor EQUAL 0)
        message(FATAL_ERROR
            "Current framework ABI must remain 1.2 with sink and activation provider ABI 1.0")
    endif()
    set(expected_epoch 0)
    foreach(epoch IN ITEMS source identity geometry evidence firmware dependency database perfcache numeric package)
        if(NOT epoch_${epoch} EQUAL expected_epoch)
            message(FATAL_ERROR "Framework epoch slot assignment changed: ${epoch}")
        endif()
        math(EXPR expected_epoch "${expected_epoch} + 1")
    endforeach()
    if(NOT context_bootstrap EQUAL 1 OR NOT context_read_only EQUAL 2
       OR NOT batch_none EQUAL 0 OR NOT stream_none EQUAL 0
       OR NOT effect_none EQUAL 0 OR NOT effect_staged EQUAL 1
       OR NOT effect_admitted EQUAL 2 OR NOT effect_activated EQUAL 3
       OR NOT activation_none EQUAL 0)
        message(FATAL_ERROR "Framework flag assignment changed")
    endif()
    if(NOT digest_algorithm STREQUAL "BLAKE3-256" OR NOT digest_bytes EQUAL 32)
        message(FATAL_ERROR "Framework digest contract changed")
    endif()

    set(LAPLACE_FRAMEWORK_MAJOR "${major}")
    set(LAPLACE_FRAMEWORK_MINOR "${minor}")
    string(TOUPPER "${epoch_source}" LAPLACE_FRAMEWORK_EPOCH_SOURCE)
    set(LAPLACE_FRAMEWORK_EPOCH_IDENTITY "${epoch_identity}")
    set(LAPLACE_FRAMEWORK_EPOCH_GEOMETRY "${epoch_geometry}")
    set(LAPLACE_FRAMEWORK_EPOCH_EVIDENCE "${epoch_evidence}")
    set(LAPLACE_FRAMEWORK_EPOCH_FIRMWARE "${epoch_firmware}")
    set(LAPLACE_FRAMEWORK_EPOCH_DEPENDENCY "${epoch_dependency}")
    set(LAPLACE_FRAMEWORK_EPOCH_DATABASE "${epoch_database}")
    set(LAPLACE_FRAMEWORK_EPOCH_PERFCACHE "${epoch_perfcache}")
    set(LAPLACE_FRAMEWORK_EPOCH_NUMERIC "${epoch_numeric}")
    set(LAPLACE_FRAMEWORK_EPOCH_PACKAGE "${epoch_package}")
    set(LAPLACE_FRAMEWORK_EPOCH_COUNT "${expected_epoch}")
    set(LAPLACE_FRAMEWORK_CONTEXT_BOOTSTRAP "${context_bootstrap}")
    set(LAPLACE_FRAMEWORK_CONTEXT_READ_ONLY "${context_read_only}")
    math(EXPR known_context_flags "${context_bootstrap} | ${context_read_only}")
    set(LAPLACE_FRAMEWORK_KNOWN_CONTEXT_FLAGS "${known_context_flags}")
    set(LAPLACE_FRAMEWORK_KNOWN_BATCH_FLAGS "${batch_none}")
    set(LAPLACE_FRAMEWORK_KNOWN_STREAM_FLAGS "${stream_none}")
    set(LAPLACE_FRAMEWORK_EFFECT_NONE "${effect_none}")
    set(LAPLACE_FRAMEWORK_EFFECT_STAGED_INERT "${effect_staged}")
    set(LAPLACE_FRAMEWORK_EFFECT_ACTIVATION_ADMITTED "${effect_admitted}")
    set(LAPLACE_FRAMEWORK_EFFECT_ACTIVATED "${effect_activated}")
    set(LAPLACE_FRAMEWORK_SINK_ABI_MAJOR "${sink_major}")
    set(LAPLACE_FRAMEWORK_SINK_ABI_MINOR "${sink_minor}")
    set(LAPLACE_FRAMEWORK_ACTIVATION_PROVIDER_ABI_MAJOR "${activation_provider_major}")
    set(LAPLACE_FRAMEWORK_ACTIVATION_PROVIDER_ABI_MINOR "${activation_provider_minor}")
    set(LAPLACE_FRAMEWORK_KNOWN_ACTIVATION_FLAGS "${activation_none}")
    set(LAPLACE_FRAMEWORK_DIGEST_BYTES "${digest_bytes}")
    get_filename_component(output_directory "${output_path}" DIRECTORY)
    file(MAKE_DIRECTORY "${output_directory}")
    configure_file(
        "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/framework.h.in"
        "${output_path}"
        @ONLY)
endfunction()
